from pathlib import Path
from Information_Units.Generators.BaseGenerator import BaseGenerator

# Example generator subclasses
class MatterGenGenerator(BaseGenerator):
    def __init__(self, generator_name, logger=None):
        super().__init__(generator_name, logger)
    
    def info(self):
        msg='Mattergen is a generative model for crystal structures developed by Microsoft.'
        return msg

    def generate(self, inputs: dict) -> str:
        # Implement generation logic here
        # For now, just simulate a path
        output_path = Path(f"/tmp/{self.generator_name}_output.cif")
        if self.logger:
            self.logger.log("Generated by MatterGen with inputs: " + str(inputs), 'info')
        return str(output_path)