from pathlib import Path
from Information_Units.Generators.BaseGenerator import BaseGenerator

# GNoME Generator implementation
class GNoME(BaseGenerator):
    def __init__(self, generator_name, logger=None):
        super().__init__(generator_name, logger)
    
    def info(self):
        msg='GNoME: Graph Networks for Materials Exploration, a deep learning framework for materials discovery'
        return msg

    def generate(self, inputs: dict) -> str:
        # Implement generation logic here
        if self.logger:
            self.logger.log("Generated by GNoME - python", 'info')

        return None